### PR TITLE
Localizer fix

### LINKED ISSUE #69: Improvements to the orbital localization code
- When localization is invoked print a small summary of which orbitals are localized
- Allow the user to decide which orbitals to localize using multiple input types:
  - by a vector of MO indices (`[10, 11, 12, 18]`)
  - By orbital space using MOInfoSpace labels (`ACTIVE`, etc.)
- Add IBO localization

### PR DESCRIPTION
**Pull request by jeffschriber**
## PR Description
Cleanup the localizer class in forte, localizer can be called as localize() with all options handled internally. Also only one option is needed now to specify localization type (default = "NONE").

**See #69 for more suggestions on how to improve the localizer.**

## PR Checklist
- [x] Cleanup handling of options
- [x] Make calling of localizer consistent in other methods 
- [x] Removed comments in code and input files
- [x] Documented source code
- [x] Checked for redundant headers
- [x] Add test case
- [x] Fixes #69
- [x] Print summary in output
- [x] Wait until directory restructure is finished
- [x] Ready to go!

### CODE REVIEW

**Comment by fevangelista** [comment]
It looks like test `aci-dsrg-mrpt2-5` is failing. Can you please check if it runs on your laptop/cluster? Also, there is a conflict that needs to be addressed.

**Comment by jeffschriber** [comment]
This test is passing on my laptop. I'll look into it a bit more and see if it passes on the cluster

File: src/orbital-helpers/localize.h [hunk 1]
```diff
@@ -44,14 +43,19 @@ namespace forte {
...
-             std::shared_ptr<ForteIntegrals> ints, std::shared_ptr<MOSpaceInfo> mo_space_info);
+             std::shared_ptr<ForteIntegrals> ints);
 
     ~LOCALIZE();
 
-    void split_localize();
 
-    void full_localize();
+    // Sets the orbitals to localize, bool to split localize
+    void set_orbital_space( std::vector<int>& orbital_spaces );
```
Comment (fevangelista) [inline src/orbital-helpers/localize.h]: This is great. Can we make it a bit more general so that it can accept a vector of vectors with the MO indices of the various groups of orbitals that we want to localize?

Comment (jeffschriber) [reply src/orbital-helpers/localize.h]: I wasn't too sure how to have a vector of vectors as an option type, but I suppose the orbital_spaces_ object could be initialized from a vector of vectors. The orbital_spaces_ vector is a read as a set of index pairs, where the pair defines the first and last orbitals in a given set to be localized together. This does require a set to contain only orbitals with continuous indices, but that seems like a reasonable requirement.

File: src/integrals/integrals.cc [hunk 2]
```diff
@@ -432,8 +432,8 @@ void ForteIntegrals::update_orbitals(std::shared_ptr<psi::Matrix> Ca,
                                      std::shared_ptr<psi::Matrix> Cb) {
 
     // 1. Copy orbitals and, if necessary, test they meet the spin restriction condition
-    Ca_->copy(Ca);
-    Cb_->copy(Cb);
+    Ca_->copy(Ca->clone());
```
Comment (tyzhang1993) [inline src/integrals/integrals.cc]: Why Ca need to be cloned here?

File: src/base_classes/README.md [hunk 3]
```diff
@@ -1,19 +1,8 @@
...
 
-
 Canonical order of base classes
 
-- StateInfo
-- SCFInfo
-- MOSpaceInfo
-- Integrals/ActiveSpaceIntegrals
-- ForteOptions
+    - StateInfo - SCFInfo - MOSpaceInfo - Integrals / ActiveSpaceIntegrals - ForteOptions
```
Comment (lcyyork) [inline src/base_classes/README.md]: This will no longer be formatted correctly.

File: src/orbital-helpers/localize.cc [hunk 4]
```diff
@@ -40,166 +40,98 @@ using namespace psi;
...
-LOCALIZE::LOCALIZE(StateInfo state, std::shared_ptr<SCFInfo> scf_info,
-                   std::shared_ptr<ForteOptions> options, std::shared_ptr<ForteIntegrals> ints,
+LOCALIZE::LOCALIZE(std::shared_ptr<ForteOptions> options, std::shared_ptr<ForteIntegrals> ints,
                    std::shared_ptr<MOSpaceInfo> mo_space_info)
-    : OrbitalTransform(scf_info, options, ints, mo_space_info), scf_info_(scf_info),
-      options_(options), ints_(ints) {
-    nfrz_ = mo_space_info->size("FROZEN_DOCC");
-    nrst_ = mo_space_info->size("RESTRICTED_DOCC");
-    namo_ = mo_space_info->size("ACTIVE");
+    : OrbitalTransform(options, ints, mo_space_info), options_(options), ints_(ints), mo_space_info_(mo_space_info) {
```
Comment (tyzhang1993) [inline src/orbital-helpers/localize.cc]: `options_` is not used anywhere, please remove this class variable.

File: src/orbital-helpers/mp2_nos.cc [hunk 5]
```diff
@@ -47,11 +47,10 @@ using namespace psi;
...
 
-MP2_NOS::MP2_NOS(StateInfo state, std::shared_ptr<SCFInfo> scf_info,
-                 std::shared_ptr<ForteOptions> options, std::shared_ptr<ForteIntegrals> ints,
-                 std::shared_ptr<MOSpaceInfo> mo_space_info)
-    : OrbitalTransform(scf_info, options, ints, mo_space_info), scf_info_(scf_info),
-      options_(options), ints_(ints), mo_space_info_(mo_space_info) {}
+MP2_NOS::MP2_NOS(std::shared_ptr<SCFInfo> scf_info, std::shared_ptr<ForteOptions> options,
+                 std::shared_ptr<ForteIntegrals> ints, std::shared_ptr<MOSpaceInfo> mo_space_info)
+    : OrbitalTransform(options, ints, mo_space_info), scf_info_(scf_info), options_(options),
+      ints_(ints), mo_space_info_(mo_space_info) {}
```
Comment (tyzhang1993) [inline src/orbital-helpers/mp2_nos.cc]: `ints_` is already in the `OrbitalTransform` superclass. Please remove.

File: src/sci/aci.cc [hunk 6]
```diff
@@ -50,7 +50,7 @@ AdaptiveCI::AdaptiveCI(StateInfo state, size_t nroot, std::shared_ptr<SCFInfo> s
                        std::shared_ptr<ForteOptions> options,
                        std::shared_ptr<MOSpaceInfo> mo_space_info,
                        std::shared_ptr<ActiveSpaceIntegrals> as_ints)
-    : ActiveSpaceMethod(state, nroot, mo_space_info, as_ints), scf_info_(scf_info),
+    : ActiveSpaceMethod(state, nroot, mo_space_info, as_ints),state_(state), scf_info_(scf_info),
```
Comment (tyzhang1993) [inline src/sci/aci.cc]: `state_` is already initialized in the superclass constructor, please remove.
